### ISSUE TITLE
ZipkinExporter cannot properly handle tags that are null

### ISSUE THREAD

**Issue by christopher-taormina-zocdoc** [open-telemetry/opentelemetry-dotnet#1095]
**Describe your environment.** Describe any aspect of your environment relevant to the problem:
* SDK version: 0.4.0-beta.111
* .NET runtime version (.NET or .NET Core, TargetFramework in the .csproj file): aspnetcore 2.1
* Platform and OS version: macos 10.14.5

It looks the ZipkinActivityConversionExtension method [ProcessTags](https://github.com/open-telemetry/opentelemetry-dotnet/blob/61d9cc2fcc5eeec79a0d604d24b0549b39b5c4b4/src/OpenTelemetry.Exporter.Zipkin/Implementation/ZipkinActivityConversionExtensions.cs#L179) does not correctly handle tags that are not strings. The HttpInListener for the AspNetCore instrumentation is setting the tag `http.status_code` to an int [here](https://github.com/open-telemetry/opentelemetry-dotnet/blob/master/src/OpenTelemetry.Instrumentation.AspNet/Implementation/HttpInListener.cs#L145). In the ProcessTags method it looks like we get the string value for the KeyValuePair that is the activity tag through this [conversion](https://github.com/open-telemetry/opentelemetry-dotnet/blob/61d9cc2fcc5eeec79a0d604d24b0549b39b5c4b4/src/OpenTelemetry.Exporter.Zipkin/Implementation/ZipkinActivityConversionExtensions.cs#L182). However this does not convert the int value of `http.status_code` to a string, which results in the code setting the tag on the ZipkinSpan to be null in this [line](https://github.com/open-telemetry/opentelemetry-dotnet/blob/61d9cc2fcc5eeec79a0d604d24b0549b39b5c4b4/src/OpenTelemetry.Exporter.Zipkin/Implementation/ZipkinActivityConversionExtensions.cs#L207). This causes a NullReferenceException when trying to write the ZipkinSpan to JSON [here](https://github.com/open-telemetry/opentelemetry-dotnet/blob/61d9cc2fcc5eeec79a0d604d24b0549b39b5c4b4/src/OpenTelemetry.Exporter.Zipkin/Implementation/ZipkinSpan.cs#L305).

**Steps to reproduce.**
Setup the AspNetCore Instrumentation to use the zipkin exporter and make a request to the server that would be sampled.

**What is the expected behavior?**
Zipkin Exporter should successfully make call to endpoint

**What is the actual behavior?**
A null reference exception is thrown when trying to convert the ZipkinSpan to json due to a null tag for `http.status_code`

**Additional context.**

**Comment by eddynaka** [comment]
@christopher-taormina-zocdoc , i will create a PR solving this issue. I will probably check if the object is string, if yes, we will maintain that logic, otherwise, it will just maintain as object. That will probably solve your issue.

**Comment by eddynaka** [comment]
@christopher-taormina-zocdoc , yesterday we merged the bugfix. Can you try the latest version in MyGet? The version would be 114. Let us know if that solves the issue, ok?
Thank you.

**Comment by christopher-taormina-zocdoc** [comment]
@eddynaka I pull 114 and I still get a null reference exception, as the `http.status_code` tag still seems to be set to null on the ZipkinSpan object

**Comment by eddynaka** [comment]
@christopher-taormina-zocdoc , after i saw, i don't know if the package 114 contains my change (we are doing nightly builds). Can you test in the new build that we will generate tonight? Looking at the tests that we made, we are covering that case.

**Comment by christopher-taormina-zocdoc** [comment]
@eddynaka about what time do those get released?

**Comment by eddynaka** [comment]
@christopher-taormina-zocdoc , it's released at 00:00 where GH Actions run. Not sure exactly what is the timezone.

Below, the tests that I'm covering: https://github.com/open-telemetry/opentelemetry-dotnet/blob/8bd8641e3e4177c25df622cfbc5b3661d2f04a0c/test/OpenTelemetry.Exporter.Zipkin.Tests/Implementation/ZipkinActivityConversionExtensionsTest.cs#L43-L57

**Comment by eddynaka** [comment]
> @eddynaka about what time do those get released?

Ok, i know the time: Wed, 19 Aug 2020 00:15:08 GMT

**Comment by christopher-taormina-zocdoc** [comment]
Hey @eddynaka , so I think this surfaced one other issue. I'm actually working with sending traces to an opentelemetry collector with a zipkin reciever. In your fix the `http.status_code` tag remains an integer which would normally be fine, but the json request for the span will keep it as an integer. This causes the opentelemetry collector to respond with a 400 because the tag value is not a string. I think since you now explicitly check for null, you can toString the `attribute.Value` on this [line](https://github.com/open-telemetry/opentelemetry-dotnet/pull/1097/files#diff-8c84d011ef62e6c07f89caa0ab54a124R180) now without worry.

**Comment by eddynaka** [comment]
@christopher-taormina-zocdoc , if that's true, we would have a bigger issue:
https://github.com/open-telemetry/opentelemetry-dotnet/blob/46907830e282ae3cc3b5890a27ce69ac4e8feeb7/src/OpenTelemetry.Exporter.Zipkin/Implementation/ZipkinSpan.cs#L283-L306

If you see this, we would convert almost every know type to their specific type.

**Comment by christopher-taormina-zocdoc** [comment]
Ok but this is exactly the behavior I just observed locally.

**Comment by eddynaka** [comment]
@christopher-taormina-zocdoc , let me test and see what is happening. Give me some time :)

**Comment by eddynaka** [comment]
@christopher-taormina-zocdoc , I tested locally with the latest version using our ConsoleExample.

Added a simple tag:
```csharp
activity?.SetTag("status", 200);
```

And, i can see the data in Zipkin:
![image](https://user-images.githubusercontent.com/16199012/90799910-49680580-e2ea-11ea-8876-fc1efde29fe8.png)

**Comment by christopher-taormina-zocdoc** [comment]
Is this using an opentelemetry collector? When I make a post to my opentelemetry collector's zipkin receiver then I receive a 400. 
```json
[
    {
        "traceId": "09d534bb0759e447b23fc947f8c0ee88",
        "name": "test/v1/values",
        "id": "5f0b9d147f4e6241",
        "kind": "SERVER",
        "timestamp": 1597935434406358,
        "duration": 11061,
        "localEndpoint": {
            "serviceName": "TestApiServer"
        },
        "annotations": [],
        "tags": {
            "http.method": "GET",
            "http.path": "/test/v1/values",
            "http.url": "http://localhost:9000/test/v1/values",
            "http.user_agent": "PostmanRuntime/7.26.3",
            "http.request_content_length": "92",
            "http.request_content_type": "application/json",
            "http.scheme": "http",
            "http.target": "/test/v1/values",
            "net.peer.port": "55206",
            "http.route": "test/v1/values",
            "span_name": "GET test/v1/values",
            "http.status_text": "OK",
            "http.response_content_type": "application/json; charset=utf-8",
            "http.status_code": 200,
            "otel.status_code": "Ok"
        }
    }
]
```

**Comment by eddynaka** [comment]
oh..i see, so u are using zipking exporter with Otel collector, is that it?

**Comment by christopher-taormina-zocdoc** [comment]
@eddynaka yeah, in our case we've dropped in the otel collector to start migrating away from zipkin, but primarily use the zipkin reciever to not change all of our existing tracing calls.

**Comment by eddynaka** [comment]
IMO, i think u should use OtelExporter instead of ZipkinExporter. We don't have a scenario that uses one exporter to send to a different collector. So, we are assuming (at least in my option), that when you use ZipkinExporter you will send data to Zipkin.

**Comment by eddynaka** [comment]
@cijothomas @CodeBlanch , have you seen this case? Do you have another suggestion?

**Comment by christopher-taormina-zocdoc** [comment]
@eddynaka the otelexporter uses grpc correct? Our current infrastructure wouldn't allow for that, as the collector is deployed behind an AWS ALB.

**Comment by christopher-taormina-zocdoc** [comment]
It also appears the the zipkin API contract states that tags should be strings. https://zipkin.io/zipkin-api/

**Comment by CodeBlanch** [comment]
I don't have any hands-on experience with it, but I don't see any reason why it shouldn't work. ZipkinExporter sends span data in Zipkin format. As long as the receiver understands that format, everything should work. So our job is to make sure we are sending valid Zipkin format. If we're not, we should fix it!

**Comment by christopher-taormina-zocdoc** [comment]
I can help out with this

**Comment by eddynaka** [comment]
IF i create a branch, can you test in ur scenario?

**Comment by eddynaka** [comment]
@christopher-taormina-zocdoc , the branch: https://github.com/open-telemetry/opentelemetry-dotnet/compare/master...eddynaka:bugfix/zipkin-format?expand=1, if u download and build you will be able to check if that works for u.

**Comment by christopher-taormina-zocdoc** [comment]
Sure let me pull that and work locally for a bit

**Comment by christopher-taormina-zocdoc** [comment]
@eddynaka It looks like that fix should work for me.

**Comment by eddynaka** [comment]
> @eddynaka It looks like that fix should work for me.

Nice to know. I openened the PR!
